title: Brighter ADHD and Neurodiversity Coaching

permalink: /blog/:year/:month/:day/:title:output_ext

sass:
  style: compressed


url: "https://brighter.coach" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap